apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: finops-db-creds-es
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: finops-db-creds-k8s
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secret/finops-db-creds
      property: username
  - secretKey: password
    remoteRef:
      key: secret/finops-db-creds
      property: password
