apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  # Finalizer ensures Application resources are deleted properly
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project defines RBAC and access controls for this application
  project: default
  
  # Source: Where the application manifests come from
  source:
    # Helm chart repository for Kyverno
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: "3.1.4"
    
    # Helm values override
    helm:
      values: |
        admissionController:
          replicas: 1
  
  # Destination: Where to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  
  # Sync Policy: How ArgoCD should sync this application
  syncPolicy:
    # ⚠️ AUTO-SYNC DISABLED for Kyverno
    # Reason: Helm post-upgrade hooks cause infinite sync loops when they fail
    # The hook job tries to pull an image that may fail, blocking ArgoCD sync indefinitely
    # Manual sync is required for Kyverno updates
    # Previous config (removed):
    # automated:
    #   prune: true
    #   selfHeal: true
    
    syncOptions:
      # Create namespace if it doesn't exist
      - CreateNamespace=true
      
      # ✅ REQUIRED: Server-side apply for large CRDs
      # Kyverno CRDs are very large and exceed the 256KB annotation limit
      # Without this, you get: "metadata.annotations: Too long: must have at most 262144 bytes"
      # Server-side apply performs diff/merge on the Kubernetes API server instead of the client
      - ServerSideApply=true
      
      # ✅ Skip Helm hooks to prevent sync loop
      # The post-upgrade hook job can fail and block ArgoCD sync
      # With SkipHooks=true, ArgoCD deploys Kyverno without executing hooks
      # Trade-off: Hook functionality (cleanup, validation) is lost, but stability is gained
      - SkipHooks=true
