apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.1.4
    chart: kyverno
    helm:
      parameters:
        - name: replicaCount
          value: "1"
        - name: admissionController.replicas
          value: "1"
        - name: backgroundController.replicas
          value: "1"
        - name: reportsController.replicas
          value: "1"
        - name: cleanupController.replicas
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipHooks=true
